### ISSUE TITLE
the size of libv8android.so is  too big, how can I find a smaller one?

### ISSUE THREAD

**Issue by 925360166** [Kudo/v8-android-buildscripts#14]
When I use the command "yarn add v8-android@7.8.2" to download the v8 engine, I find the size of v8-android-7.8.2.aar is 29.4MB,  while android-jsc-r245459.aar is just 12.5MB。

The size of our android project is huge, so I'm afraid I can't afford any increase in the engine's size, 
So how can I find a smaller v8？
Could U please upload a smaller to npm?

Looking forward to hearing from you~

**Comment by Kudo** [comment]
If you don't use JavaScript `Intl`, you may consider to use `v8-android-nointl` variants.
The AAR size is about 18MB.

Well, the AAR contains four libandroid.so (armeabi-v7a, x86, arm64-v8a, x86_64)
Supposedly you are publishing a per architecture APK, 
[i.e. set the `enableSeparateBuildPerCPUArchitecture` to true in android/app/build.gradle.](https://github.com/facebook/react-native/blob/master/template/android/app/build.gradle#L94)
Your APK size could be smaller.

On the other hand, it is true that V8 binary size is bigger compared to JSC.
If you really care about the binary size, please consider to use Hermes.
Hermes's binary size is dramatically smaller than V8 and JSC.
