### ISSUE TITLE
enable pointer compression for android

### ISSUE THREAD

**Issue by gengjiawen** [Kudo/v8-android-buildscripts#15]
Ref: https://docs.google.com/document/d/10qh2-b4C5OtSg-xLwyZpEI5ZihVBPtn1xwKBbQC26yI/edit#.

**Comment by Kudo** [comment]
Hey @gengjiawen, the feature should be covered on arm64 variant after v8-android 8.80.

**Comment by gengjiawen** [comment]
I am not seeing it in gn args 
https://github.com/Kudo/v8-android-buildscripts/blob/3d2db6162957dab32a85622ccc21b70a6c97d8da/scripts/build.sh#L6

Anything I miss ?
