### ISSUE TITLE
Could I build v8.so on MacOS?

### ISSUE THREAD

**Issue by dongzhong** [Kudo/v8-android-buildscripts#18]

**Comment by Kudo** [comment]
For v8-ios, the answer is definitely yes.
For v8-android, supposedly yes, the script will download android NDK for macOS accordingly, but I didn't test before.

**Comment by dongzhong** [comment]
> For v8-ios, the answer is definitely yes.
> For v8-android, supposedly yes, the script will download android NDK for macOS accordingly, but I didn't test before.

Thank you for reply.
I have tried to build v8-android from official source on MacOS. Only for 64bit-architecture is OK, while 32bit failed.
Maybe I should find a Linux machine to continue.

**Comment by Kudo** [comment]
closing this issue. let me know if you still encounter this problem.
