### ISSUE TITLE
App crash on startup with v7.8.0

### ISSUE THREAD

**Issue by bhaskarGyan** [Kudo/v8-android-buildscripts#2]
App is crashing on startup with v8-android version 7.8.0. It is working fine with v7.5.1.

# React Native Version
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 241.96 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    **react-native: 0.60.4 => 0.60.4** 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
    react-native-wm-utils: 1.0.10

## Stacktrace
D/ReactNative(23345): ReactInstanceManager.recreateReactContextInBackgroundInner()
D/ReactNative(23345): ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
D/ReactNative(23345): ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative(23345): ReactInstanceManager.runCreateReactContextOnNewThread()
D/SoLoader(23345): About to load: libhermes.so
D/SoLoader(23345): libhermes.so not found on /data/data/com.-.-/lib-main
D/SoLoader(23345): libhermes.so not found on /data/app/com.-.-/lib/arm
D/SoLoader(23345): libhermes.so not found on /system/vendor/lib
D/SoLoader(23345): libhermes.so not found on /system/lib
E/SoLoader(23345): couldn't find DSO to load: libhermes.so
E/AndroidRuntime(23345): FATAL EXCEPTION: create_react_context
E/AndroidRuntime(23345): Process: com.-.-, PID: 23345
E/AndroidRuntime(23345): java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
E/AndroidRuntime(23345): at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
E/AndroidRuntime(23345): at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
E/AndroidRuntime(23345): at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
E/AndroidRuntime(23345): at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
E/AndroidRuntime(23345): at com.facebook.hermes.reactexecutor.HermesExecutor.(HermesExecutor.java:20)
E/AndroidRuntime(23345): at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)

**Comment by Kudo** [comment]
I am sorry to introduce breaking change, please try to upgrade react-native-v8 as well.

Breaking Changes

Since V8 did change their embedder API interface, original react-native-v8 will access to non existing symbol and crash.
Please upgrade react-native-v8 to one of these version.

v0.59.10-patch.3
v0.60.6-patch.1
v0.61.1-patch.2
v0.61.2-patch.0
v0.61.3-patch.0
v0.61.4-patch.0
