### ISSUE TITLE
Build on Mac OS need input password

### ISSUE THREAD

**Issue by xiebudong** [Kudo/v8-android-buildscripts#27]
![image](https://user-images.githubusercontent.com/3848929/146148582-247b22c3-9573-444b-92bc-ebb3fc12ba77.png)

I'm trying to build v8 so library for Android on Mac.  When running 'yarn setup' the progress is stuck at need input a password. What is the password,  how can get the password? Thanks!

**Comment by Kudo** [comment]
sorry being late for this. i think it's your sudo password. v8 requires more building tools to install on your host.
