### ISSUE TITLE
Cache build setup by v8 version

### ISSUE THREAD

**Issue by sirpy** [Kudo/v8-android-buildscripts#8]
We can cache in circle ci the setup step if the v8 version didnt change

**Comment by Kudo** [comment]
Good idea especially after joining the JIT build.
However, I am planning to migrate GitHub Actions. Maybe to do that after the migration.

**Comment by Kudo** [comment]
right now the ci is using github action already. however, the downloaded v8 sources from `gclient sync` exceeded github cache limit 😞  i just give up for this.
thanks for the great recommendation anyway 👍
